#! /usr/bin/python3.9

from .exceptions import CATIAApplicationException

# Auto-generated imports

__all__ = ['CATIAApplicationException']
